
bailian.model=deepseek-v3
bailian.endpoint=https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions

asr.aliyun.token=
asr.aliyun.endpoint=wss://nls-gateway-cn-shanghai.aliyuncs.com/ws/v1
asr.minAutoAnalyzeLength=6
